// <auto-generated />
namespace FitCard.DesafioPratico.DAL.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CamposExtrasEstabelecimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamposExtrasEstabelecimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201901250146555_CamposExtrasEstabelecimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
